In [1]:
import numpy as np
import pandas as pd

In [2]:
# 1 How likely is it that you roll doubles when rolling two dice?

n_trials = 100_000
outcome = [1, 2, 3, 4, 5, 6]

rolls = np.random.choice(outcome, size=(n_trials, 2))

rolls

array([[2, 3],
       [3, 4],
       [1, 6],
       ...,
       [1, 3],
       [4, 3],
       [3, 4]])

In [3]:
die1 = np.random.choice(outcome, size = n_trials)
die2 = np.random.choice(outcome, size = n_trials)

doubles = die1 == die2
doubles.mean()

0.16631

In [4]:
# 2 If you flip 8 coins, what is the probability of getting exactly 3 heads? 
# What is the probability of getting more than 3 heads?

n_trials = nrows = 100_000
n_coins = ncols = 8

flips = np.random.choice([1,0],n_trials * n_coins).reshape(nrows,ncols)
flips = pd.DataFrame(flips)
flips

three_heads = flips.sum(axis=1) == 3
three_heads.mean()

0.22007

In [5]:
# 3 There are approximitely 3 web development cohorts for every 1 data science cohort at Codeup. 
# Assuming that Codeup randomly selects an alumni to put on a billboard, 
# what are the odds that the two billboards I drive past both have data science students on them?

outcomes = [1,0]
board1 = np.random.choice([1,0], size=(100_000, 2), p =[0.75,0.25])
board2 = np.random.choice([1,0], size=(100_000, 2), p =[0.75,0.25])

prob_of_zeros = (board1 == [0,0]) & (board2 == [0,0])
prob_of_zeros.mean()

0.062875

In [6]:
# 4 Codeup students buy, on average, 3 poptart packages (+- 1.5) a day from the snack vending machine. 
# If on monday the machine is restocked with 17 poptart packages, 
# how likely is it that I will be able to buy some poptarts on Friday afternoon?

n_trials = nrows = 100_000
n_days = ncols = 5

#np.random.normal(loc = mean, scale = std, size = rows, columns)
poptarts = np.random.normal(3, 1.5,(nrows,ncols))
poptarts = pd.DataFrame(poptarts)

pop_tarts_sum = poptarts.sum(axis=1)
pop_tarts_sum

0        15.657674
1        15.296289
2        14.710887
3        19.243520
4        14.255598
           ...    
99995    15.341805
99996     8.132730
99997    15.534415
99998    16.351044
99999    12.860487
Length: 100000, dtype: float64

In [7]:
gonna_eat = pop_tarts_sum < 17
gonna_eat

0         True
1         True
2         True
3        False
4         True
         ...  
99995     True
99996     True
99997     True
99998     True
99999     True
Length: 100000, dtype: bool

In [8]:
gonna_eat.mean()

0.72625

In [9]:
# 5  Compare Heights
# Men have an average height of 178 cm and standard deviation of 8cm.
# Women have a mean of 170, sd = 6cm.
# Since you have means and standard deviations, you can use np.random.normal to generate observations.
# If a man and woman are chosen at random, P(woman taller than man)?

n_trials = 10000000

men = np.random.normal(178,8,size = n_trials)
women = np.random.normal(170,6,size = n_trials)

woman_taller = women > men
woman_taller.mean()

0.2119304

In [10]:
# 6 When installing anaconda on a student's computer, there's a 1 in 250 chance that the download is corrupted and the installation fails. 
# What are the odds that after having 50 students download anaconda, no one has an installation issue? 100 students?

# 1 in 50
odds = 1/250
students = ncols = 50
n_trials = nrows = 1000000
outcomes = [1,0]
p_outcomes = [odds, 1 - odds]

installs = np.random.choice(outcomes, (nrows,ncols), p=p_outcomes)
installs = pd.DataFrame(installs)
installs

success = installs.sum(axis=1) < 1
success.mean()

0.818884

In [11]:
# 1 in 100
odds = 1/250
students = ncols = 100
n_trials = nrows = 1000000
outcomes = [1,0]
p_outcomes = [odds, 1 - odds]

installs = np.random.choice(outcomes, (nrows,ncols), p=p_outcomes)
installs = pd.DataFrame(installs)
installs

success = installs.sum(axis=1) < 1
success.mean()

0.669948

In [12]:
# Probability we see an issue in 150
odds = 1/250
students = ncols = 150
n_trials = nrows = 1000000
outcomes = [1,0]
p_outcomes = [odds, 1 - odds]

installs = np.random.choice(outcomes, (nrows,ncols), p=p_outcomes)
installs = pd.DataFrame(installs)
installs

success = installs.sum(axis=1) >= 1
success.mean()

0.451812

In [13]:
#450 with no issue?
odds = 1/250
students = ncols = 450
n_trials = nrows = 1000000
outcomes = [1,0]
p_outcomes = [odds, 1 - odds]

installs = np.random.choice(outcomes, (nrows,ncols), p=p_outcomes)
installs = pd.DataFrame(installs)
installs

success = installs.sum(axis=1) < 1
success.mean()

0.165176

In [14]:
# 7 There's a 70% chance on any given day that there will be at least one food truck at Travis Park. 
# However, you haven't seen a food truck there in 3 days. How unlikely is this?

p_truck = (0.7,0.3)
days = ncols = 3
trials = nrows = 10000
outcomes = [1,0]

no_trucks = np.random.choice(outcomes,(nrows,ncols), p=p_truck)
no_trucks

array([[1, 0, 1],
       [1, 1, 1],
       [1, 1, 0],
       ...,
       [1, 1, 1],
       [0, 1, 1],
       [1, 1, 1]])

In [15]:
no_trucks = pd.DataFrame(no_trucks)

In [16]:
# How unlikely?
p_no_trucks_three_days = no_trucks.sum(axis=1) == 0
p_no_trucks_three_days.mean()

0.0265

In [17]:
# How likely that a truck shows up sometime this week?
p_truck = (0.7,0.3)
days = ncols = 7
trials = nrows = 100_000
outcomes = [1,0]

truck_shows_up = np.random.choice(outcomes,(nrows,ncols), p=p_truck)
truck_shows_up

array([[1, 0, 0, ..., 0, 1, 0],
       [0, 0, 0, ..., 1, 1, 0],
       [0, 1, 1, ..., 1, 1, 1],
       ...,
       [1, 1, 0, ..., 1, 0, 1],
       [0, 1, 1, ..., 1, 1, 0],
       [1, 1, 1, ..., 1, 1, 0]])

In [18]:
truck_shows_up = pd.DataFrame(truck_shows_up)
truck_shows_up

0  1  2  3  4  5  6
0      1  0  0  1  0  1  0
1      0  0  0  0  1  1  0
2      0  1  1  1  1  1  1
3      1  1  0  1  0  0  0
4      0  1  0  1  1  1  1
...   .. .. .. .. .. .. ..
99995  1  1  1  1  0  1  1
99996  1  1  1  0  1  0  0
99997  1  1  0  1  1  0  1
99998  0  1  1  0  1  1  0
99999  1  1  1  0  1  1  0

[100000 rows x 7 columns]

In [19]:
p_truck_shows_up = truck_shows_up.sum(axis=1) != 0
p_truck_shows_up.mean()

0.99972

In [20]:
#8 If 23 people are in the same room, what are the odds that two of them share a birthday? 
# What if it's 20 people? 40?

n_people = ncols = 23
n_trials = nrows = 10000
days = range(365)

bdays = np.random.choice(days, size=(nrows,ncols))
bdays = pd.DataFrame(bdays)
bdays.apply(lambda row: row.is_unique, axis=1).mean()

0.4887

In [21]:
n_people = ncols = 20
n_trials = nrows = 10000
days = range(365)

bdays = np.random.choice(days, size=(nrows,ncols))
bdays = pd.DataFrame(bdays)
bdays.apply(lambda row: row.is_unique, axis=1).mean()

0.5871

In [22]:
n_people = ncols = 40
n_trials = nrows = 10000
days = range(365)

bdays = np.random.choice(days, size=(nrows,ncols))
bdays = pd.DataFrame(bdays)
bdays.apply(lambda row: row.is_unique, axis=1).mean()

0.1107

In [23]:
# df['at_least_two_matching_birthdays'] = df.nunique(axis=1) < ncols
# adds a column to the DataFrame that returns boolean values